---
- name: Install erlang
  package:
    name: erlang
    state: present

- name: Include Debian tasks
  include_tasks: "Debian.yml"
  when: (ansible_os_family == "Debian" and ansible_distribution_release != "focal" and ansible_distribution_release != "bullseye" )

- name: Include Ubuntu2004 tasks
  include_tasks: "Focal.yml"
  when: ansible_distribution_release == "focal"

- name: Include Debian Bullseye tasks
  include_tasks: "Bullseye.yml"
  when: ansible_distribution_release == "bullseye"

- name: Include Centos7 install tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "8"

- name: Include Centos8 install tasks
  include_tasks: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"

- name: Ensure rabbitmq vhosts
  rabbitmq_vhost:
    name: "{{ item }}"
  with_items: "{{ rabbitmq_vhosts }}"

- name: Ensure the users present
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    vhost: "{{ item.vhost | default('/') }}"
    tags: "{{ item.tags | default('') }}"
  with_items: "{{ rabbitmq_users }}"

- name: Ensure the users removed
  rabbitmq_user:
    user: "{{ item }}"
    state: absent
  with_items: "{{ rabbitmq_users_remove }}"
