---
- name: facts
  setup:
  when: ansible_os_family is not defined

- name: Install erlang
  package:
    name: erlang
    state: present

- name: Include Debian tasks
  include_tasks: "Debian.yml"
  when: (ansible_os_family == "Debian" and ansible_distribution_release != "focal" and ansible_distribution_release != "bullseye" )

- name: Include Ubuntu2004 tasks
  include_tasks: "Focal.yml"
  when: ansible_distribution_release == "focal"

- name: Include Debian Bullseye tasks
  include_tasks: "Bullseye.yml"
  when: ansible_distribution_release == "bullseye"

- name: Include Centos7 install tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "8"

- name: Include Centos8 install tasks
  include_tasks: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: rabbitmqi.conf
  template:
    src: rabbitmq.conf.j2
    dest: "{{ rabbitmq_cfg_file }}"
    mode: 0644
    owner: root
    group: root
  when: rabbitmq_cfg_settings
  notify: restart rabbitmq

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"
