---
- name: Install erlang
  package:
    name: erlang
    state: present

- name: Include Debian tasks
  include_tasks: "Debian.yml"
  when: (ansible_os_family == "Debian" and ansible_distribution_release != "focal")

- name: Include Ubuntu2004 tasks
  include_tasks: "Focal.yml"
  when: ansible_distribution_release == "focal"

- name: Include Centos6 and Centos7 install tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "8"

- name: Include Centos8 install tasks
  include_tasks: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"
