---
- name: Add packagecloud GPG key.
  rpm_key:
    key: "{{ rabbitmq_gpg_key }}"
    state: present

- name: Download RabbitMQ package.
  get_url:
    url: "{{ rabbitmq_rpm_url }}"
    dest: "/tmp/{{ rabbitmq_rpm }}"

- name: Ensure RabbitMQ is installed.
  yum:
    name: "/tmp/{{ rabbitmq_rpm }}"
    state: "present"
