---
- name: Install required packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - yum-utils

- name: Create repository file in /etc/yum.repos.d/
  ansible.builtin.template:
    src: rabbitmq_erlang.repo.j2
    dest: /etc/yum.repos.d/rabbitmq_erlang.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Erlang {{ erlang_version }}
  ansible.builtin.yum:
    name: erlang-{{ erlang_version }}
    state: present
    update_cache: true
    enablerepo:
      - rabbitmq_erlang
    
- name: Install RabbitMQ {{ rabbitmq_version }}
  ansible.builtin.yum:
    name: rabbitmq-server-{{ rabbitmq_version }}
    state: present
    update_cache: true
    enablerepo:
      - rabbitmq_erlang

- name: Prevent Erlang and RabbitMQ from being upgraded
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    line: "exclude=erlang* rabbitmq-server*"
    state: present
