---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO:-ubuntu2004}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: 
      ${MOLECULE_DOCKER_COMMAND:-""} 
      /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    capabilities: 
      - SYS_ADMIN
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: ${MOLECULE_NO_LOG:-true}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
