---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${MOLECULE_DISTRO}"
    image: "${MOLECULE_DISTRO}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: ${MOLECULE_NO_LOG:-true}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
