---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Creates directory for java
      file:
        path: /usr/share/man/man1
        state: directory

    - name: Update cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      changed_when: false
      failed_when: false
